import logging as log

log.info('99 bottles of beer on the wall')
log.error('one of them happen to fall')

# Output <1>
# ERROR:root:one of them happen to fall <2>
